Add GitHub Actions CI with ROS dependency resolution
loco-3d/crocoddyl pull request #935
Opened 2021-04-23 21:35 UTC by wxmerkt

This adds a GitHub Actions-based CI on 18.04 and 20.04 resolving Pinocchio/EigenPy via ROS and using catkin tools to build and run tests on Crocoddyl. Part of the motivation is that a) Travis is being phased out, b) Crocoddyl can and is being used within ROS workspaces e.g. for robot deployment, and c) that RobotPkg without staging fails CI jobs every now and then when packages are out of sync (e.g. in #932 and #931 right now). This augments the more extensive coverage and set of configurations Gepgitlab is providing and is more of a stand-in replacement for Travis.

2021-04-23 23:37 UTC, cmastalli approved these changes
This is really nice and useful. Thanks @wxmerkt ;)

2021-04-23 23:44 UTC, nim65s requested changes
Thanks for this !

This is currently failing because the submodule for example-robot-data is missing, but I guess this is easy to fix.

2021-04-24 05:21 UTC, jcarpent commented
@wxmerkt in your current setup, there is currently no build. Am I missing something?

2021-04-24 05:22 UTC, jcarpent commented
Additionally, it would be nice to also do it on Pinocchio, hpp-fcl and eigenpy.

2021-04-24 13:36 UTC, wxmerkt commented
Thank you for the feedback and comments. I do plan to add it to eigenpy, pinocchio, hpp-fcl once this one here succeeds. I've added recursive submodule checkouts now so hope the build will pass (https://github.com/wxmerkt/crocoddyl/actions/runs/780608212).

@jcarpent It uses [industrial-ci](https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst) which runs the build in a Docker - as thus I don't need to manually specify the build step manually

2021-04-24 14:18 UTC, nim65s approved these changes
LGTM, thanks !

Plus 30min is a nice build time :)

2021-04-25 21:29 UTC, proyan commented
With this new CI check, we could allow travis to fail. Could you please do this here @wxmerkt ?

2021-04-26 07:38 UTC, merged