Fixed notebook as reported in #970
loco-3d/crocoddyl pull request #971
Opened 2021-06-28 22:04 UTC by cmastalli

2021-06-28 22:04 UTC, hrp2-14 commented
Hi ! This project doesn't usually accept pull requests on master. If this wasn't intentionnal, you can change the base branch of this pull request to devel (No need to close it for that). Best, a bot.

2021-07-02 13:03 UTC, proyan requested changes
Thanks for the fix Carlos.

2021-07-02 13:03 UTC, proyan commented on examples/notebooks/introduction_to_crocoddyl.ipynb
> +    "frameTranslationResidual = crocoddyl.ResidualModelFrameTranslation(state,\n",
Residual Models are not yet released on master branch. This won't work.

2021-07-02 13:04 UTC, proyan commented on examples/notebooks/introduction_to_crocoddyl.ipynb
> +    "frameTranslationResidual = crocoddyl.ResidualModelFrameTranslation(state,\n",
Ah the branch was changed to devel. My bad

2021-07-02 13:08 UTC, proyan approved these changes

2021-07-02 13:08 UTC, merged